DROP TABLE IF EXISTS BATCH;
DROP TABLE IF EXISTS PLANT;
DROP TABLE IF EXISTS LOCATION_BATCH;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS PROJECT_LOCATION;
DROP TABLE IF EXISTS CLIENT_LOCATION;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS CLIENT_PROJECT;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS PROBLEM_BATCH;

CREATE TABLE BATCH (
	BATCH_ID SERIAL PRIMARY KEY,
	RFID TEXT,
	CREATION_DATE DATE,
	PLANT_ID INT,
);

CREATE TABLE PROBLEM_BATCH (
	PROBLEM_BATCH_ID SERIAL PRIMARY KEY,
	BATCH_ID INT,
	RESOLVED BOOLEAN
);

CREATE TABLE PLANT(
	PLANT_ID SERIAL PRIMARY KEY,
	PLANT_NAME TEXT
);

CREATE TABLE LOCATION_BATCH (
	LOCATION_BATCH_ID SERIAL PRIMARY KEY,
	ARRIVAL_DATE DATE,
	BATCH_ID INT,
	LOCATION_ID INT
);

CREATE TABLE LOCATION (
	LOCATION_ID SERIAL PRIMARY KEY,
	LOCATION_NAME TEXT
);

CREATE TABLE PROJECT_LOCATION (
	PROJECT_LOCATION_ID SERIAL PRIMARY KEY,
	PROJECT_ID INT,
	LOCATION_ID INT
);

CREATE TABLE CLIENT_LOCATION (
	CLIENT_LOCATION_ID SERIAL PRIMARY KEY,
	LOCATION_ID INT,
	CLIENT_ID INT
);

CREATE TABLE CLIENT(
	CLIENT_ID SERIAL PRIMARY KEY,
	CLIENT_NAME TEXT,
	CLIENT_PHONE TEXT,
	CLIENT_EMAIL TEXT
);

CREATE TABLE CLIENT_PROJECT (
	CLIENT_PROJECT_ID SERIAL PRIMARY KEY,
	CLIENT_ID INT,
	PROJECT_ID INT
);

CREATE TABLE PROJECT (
	PROJECT_ID SERIAL PRIMARY KEY,
	PROJECT_NAME TEXT
);
